apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: sync-alert
  namespace: flux-system
spec:
  providerRef:
    name: github-provider
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: anubis-app-delivery-source
