apiVersion: v1
kind: Secret
metadata:
  name: flux-system
  namespace: flux-system
type: Opaque
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDVkdlN3YyUXBUWm9Xa1YvSEFOQ2pKMWVlYjZvRjRkNktEYVV6YjVsaC9HUUFBQUppVERxU3lrdzZrCnNnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ1ZHZTd2MlFwVFpvV2tWL0hBTkNqSjFlZWI2b0Y0ZDZLRGFVemI1bGgvR1EKQUFBRUFVRyt1NWZZMmhrVlM3UzBtS1hGU3MvTUp6NTByYkpNeWl2V2NwbzFsK1paVVo3dS9aQ2xObWhhUlg4Y0EwS01uVgo1NXZxZ1hoM29vTnBUTnZtV0g4WkFBQUFGR1J1YW1GemNHVnlRR2h2ZEcxaGFXd3VZMjl0QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
    -----END OPENSSH PRIVATE KEY-----

  identity.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJUZ7u/ZClNmhaRX8cA0KMnV55vqgXh3ooNpTNvmWH8Z dnjasper@hotmail.com

  known_hosts: |
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAA...