apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
data:
    identity: ENC[AES256_GCM,data:elZ5CpoxHz47XXKu4fR9v1x1Vb9g81DhADB+B87xTtvQnIrF3iRmUeb79dEi94vGNYj44y4NwP9mktziICvfq51N2unSw6ZvhOi4d0togc8aTkr89Zl58AmbbCWaA+4rPrHnZqT2wau9hmo4AQq3K1Aq/THuva4w9l54+jcHhB2j6QUeXXSfgGucv2T4XcnNamZ1mX9uyzVtX8W/TMnHXxs1YQqX4xrAyFUwCZ2mjBGqYjVvqa/9KzWueD/lL0z1VdRG6WzCdLUgYdTZT9sQUKXdBQskI6LNeSy6BzirHL2pgbz3Klzq5R0J3oXeqxveQuHBu+x4eYZ7+cUnFuNZ/Bw/xZsBAuoIcKHS4NVCfSlWKyd8jrhBHfhuYEIST/5SCZO0nPw2tcuXMF1wbBF2EdNt6quLF3B3dLOtK249K3eiAXkp3A21Nt5sUDyIGRYcPIe4aN5TFnFq8mQ+tbjVcCMkXsClzGsuoAu9nLdv3E5rv9OQ66kWCqIZyzTW69Zj06aTT8bEabsIsQYQ4cOmK7ARAIJnEhnaUx+xdRbo180LwVCZCNwTQ/koyQo4+cgmhzpAvTvAIP9W1Wk/WjQ+plFSRrkuRHZ+PSznHGtlbGeu3LGtWNijOYFccxcF2ABsWyXzS7XBqncpdH6bxE1B0NWaT/cQWBUzg5grFcSBz2s+EXO6oL+ounEBDRMBd6i/ShuxrTiZsrf6lP+ieOW4vvXEgOI=,iv:hrUPOr0HLe/F1ypHR8tSpiESqyBzFvDM3ChnZ6kjcZo=,tag:c2p5CNawT/OxxsuY++wjQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:OvNR09MFArl5ntBWXQLxfHRDyfPvGdfjWm27aJP612W/+tRC3iyew2oxkyqyG98AYbdjBQKVZRdKjta6CcFqvHaznmqaX5OkF3oPwNQN80pCe6p39ffDozhPot3tUJauZezMPrHiFAEkaynVXJ2bvgFwYb14KaqVVw7GlD4EPixkWWI1heglQw==,iv:f/6yAx+u2CgqDao6yzDe1rzQG/a4RQm8PHp5gHJEa2k=,tag:jcLLKWDmeSAQkOhb1PGRDA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:533267265715:key/256f7fa0-9e7e-4790-8717-6886aff5b4b7
          created_at: "2026-06-08T23:59:45Z"
          enc: AQICAHjxJHNQh4CDBH5ZHGh2SdRPFYJ11w2z2Hrxtvk+V4R0YAGEnX9myq8/Ojyh0Ejz52OqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHiO7PVVy6ds8NVIRAgEQgDuPjh8gnh1LwmQHjSyKEO38n+ZIIhJXyHD8fxmQS02sSBoNMkhdY1hulIiWmFdveMy4Ag97/nx+bI4t8w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-08T23:59:47Z"
    mac: ENC[AES256_GCM,data:xxfN2uPSlE4/cWkJtEakl3WmUjJ5SD5Vtd1xdPBysqFR7nt0+tGYHgWfq0vIUoqBHpWyzJj2FK5mXvhYsZ0YVz3MKtdAErwx/DIwbPZ31Ty9iLNxfWz7YmQjHK6G9laE5uHMgHTJ53fF4b0QYrMm/L1Nljc1W3mjC0MWo98aN5c=,iv:RjXhPmcZvXCcFJcO+CTPbv31PFarku/3n+YSzRvnKM4=,tag:4rVtVw18YG/ibgykyX47lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
