apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system # ◄ MATCHES THE ROOT SYSTEM OBJECT EXACTLY
  namespace: flux-system
spec:
  interval: 5m
  path: ./aws-load-balancer-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # ◄ THE MASTER WIRE: Gives the root system permission to decrypt files!
  decryption:
    provider: sops
