apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:GBix3zVqAlvyzgSxeokmtORDl+hiMzK51YR/faNVT3wvBfWQKEJXuc5ULHCAVg71Gy08lGbVObZ6ct/gJoQGagP1wM8uQdZo7Ow8jHIueBzlgNNbbhuqL2aBWzz2vwEE2uFffu50LRuFWmZxLdd0TufEFJgH2sYAC2Wm64YCh5hwXJPJ6LNq1tAF5ofG34CiI0x3ikfP7Ve3qeZ171WWo18OD/+N+kYWys5mH/jULtCdFwl5uHaJKcYJ03WVCDswe+MKPZE/aNkoZDM3v8237uhBPYP5g6Hw6xPvDJMnIx+O9ACUHEcRbWXWF5OwFvP81P4/lhYidZ4dEfpaNs1HNnrnoGhHoqwg+cR5uI50yuYpYEpI1vZsTRthVsIFANIk8Gr5zAVjylPbXr75XIMnfSTgvofZypZMajmUDc93IimP+e9VJ2sBTQsdhLOUdDrRDb8w3/xfdSrAr2cHkGqZjGWZxgqYHYjO7S6zfKDiD6FXmERSL/MlAIYJfAGV/BPXZ6kYVk7k+ut+XjwOyKNL+Rdy01XHhIgFvFHfZZjCbJ6VHOMIxvg9NTRT7ubbNh8VfRC3Gr1PuOk6BF/fSz7SmjaTr5EVKJU+qWL0A2VESgiNnxEHPNmOCzXH8yPh8ORY6p2AUV6smC2FrpTLHJv7ZMpaqZoyDpMRgwDoeQ4SxLWXVvHRgbJ/2D2kAz8USTe3aBWkPqaf8Gz0lxb1rDf/oORVBHgIvJQ2DZnlqxEYSEyWjXHNZamJhfXBZAera5IYVFXWSnuaT2OYngzN/JnAZNshtncp8mtX118iCjtnf7O94OO8xjXbmtL3jQ==,iv:PC+SCiw6eHjaFdcwIfaXTq+ATnokimnElRNQySWpBLA=,tag:58+odCgH+yrMjxnd7pGWrA==,type:str]
    identity.pub: ENC[AES256_GCM,data:3V1waytOCLg2Vm9wV0PLYntfZPfBdBWU/oKSw9rU9XPWItwgPi7vKPiAHd9Gr/1/wGjJ7+dbh1COI9HXGBeGaw1igtfh+5yUxvqiwvjjxs3G2VB0PVboYbT6iYQxtcp7Ppk2/xgm,iv:s2q4wBUWR4XxtkhVhFRP3S1CqXNKgSGeJZ/iT+AEJAU=,tag:CiG5Ek/MmHyJIHzxU72S8w==,type:str]
    known_hosts: ENC[AES256_GCM,data:K3EBgFEKJhSXaA2zt+8kVEgLA4gDQZBRyjW0Lc2Rm0C+39Vm+FXzKTRjBGdtcahfijQ=,iv:04Op8Ul/WLkzSzlB2Y3Uka18AX5TjG5wxQYrDi80CZ8=,tag:kmTYNcgC+AAtWSCtdqLl8w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:533267265715:key/256f7fa0-9e7e-4790-8717-6886aff5b4b7
          created_at: "2026-06-09T03:23:27Z"
          enc: AQICAHjxJHNQh4CDBH5ZHGh2SdRPFYJ11w2z2Hrxtvk+V4R0YAH5jlp7l9tPEcW36lCLcta9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcI8b86MZINnc9Hr1AgEQgDtlMjGEF2LDS26jgckMk5cqY6PD+f7ZmyN37JWJbX5u7eCnmbZsL1kCovR1dtll1G3CwOHxzZssFk1ezw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-09T03:23:29Z"
    mac: ENC[AES256_GCM,data:TzmJDMjsSzVTgVYZrnftJyMQNwx2zJ+apDPuU9DlhVJuVOEmj0wQX1vOFLYKOcsTnTJwlJ4pVhlK4UveBEuRlykiznF+uezwmSLHyD8HnH0w+FLCQQ44x03MSWA10M9XT93ASe0L6vwgwXoj88lCv1/yJH4F5C2t2juwPq6cJhE=,iv:XAnLG11vhU8+FfWE4bELORtPOgRjgABPg0dJ3N49fWE=,tag:lRofHvJVmT4SM1QCtcf96g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
