apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: eks
  namespace: kube-system
spec:
#  url: https://aws.github.io/eks-charts
  url: ssh://git@://github.com


  interval: 1h # I love you Brotha