apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-provider
  namespace: flux-system
spec:
  type: githubdispatch
#  address: https://github.com/dnjasper/anubis-app-delivery
  address: https://github.com
  secretRef:
   # name: github-webhook-token
    name: flux-system  # I love you DJ
