apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Receiver
metadata:
  name: github-receiver
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: flux-system # Reuses your existing bootstrap secret for token validation
  resources:
    - kind: GitRepository
      name: anubis-app-delivery-source
